name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   
      run: |
        echo inizio login 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
         echo fine login

    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag chico230/docker-graphql:0.0.1 
       docker build . --file Dockerfile --tag chico230/docker-graphql
    - name: Push the Docker image
      run: |
        docker push chico230/docker-graphql:0.0.1
        docker push chico230/docker-graphql:lastest
